#!/usr/bin/env python3
# FILE: sync_agent_docs.py
# SUMMARY: Generate or verify the agent instruction wrappers from the shared agent rules source.

from __future__ import annotations

import argparse
import re
from pathlib import Path

from ai_context.rendering import render_json

ROOT_DIR = Path(__file__).resolve().parent.parent
SHARED_RULES_PATH = ROOT_DIR / "docs" / "agent_rules.md"
CLAUDE_PATH = ROOT_DIR / "CLAUDE.md"
AGENTS_PATH = ROOT_DIR / "AGENTS.md"
# Codex reads AGENTS.md, Claude Code reads CLAUDE.md, neither reads the other; docs/agent_rules.md
# is the one source both render from — a dict entry, not a symlink git on Windows would mangle.
WRAPPER_READERS = {CLAUDE_PATH: "Claude Code", AGENTS_PATH: "Codex"}
_HAND_PLACED_SECTION_TITLES = ("Start here", "Working notes", "Task process")
_SECTIONS_RENDERED_SEPARATELY = frozenset(_HAND_PLACED_SECTION_TITLES)
_NAMED_SECTION_PATTERN = re.compile(r"^([A-Z][^:\n]*):\n((?:- .+\n?)+)", re.MULTILINE)
DROPPED_SECTION_RULE_ID = "drift.agent_docs.section_dropped"
_NEXT_COMMANDS = [
    "uv run python scripts/sync_agent_docs.py",
    "uv run python scripts/sync_agent_docs.py --check",
]


# FUNCTION: render_python_versions
# SUMMARY: Read the runtime minimum and dev toolchain version from their own files, not typed by hand.
def render_python_versions() -> tuple[str, str]:
    pyproject = (ROOT_DIR / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^requires-python\s*=\s*">=([0-9.]+)"', pyproject, re.MULTILINE)
    if match is None:
        raise RuntimeError('pyproject.toml has no `requires-python = ">=X.Y"` entry to read.')
    toolchain = (ROOT_DIR / ".python-version").read_text(encoding="utf-8").strip()
    return match.group(1), toolchain


# FUNCTION: _display_path
# SUMMARY: Render a path relative to the repository root when possible, else the absolute path.
def _display_path(path: Path) -> str:
    return str(path.relative_to(ROOT_DIR)) if path.is_relative_to(ROOT_DIR) else str(path)


# FUNCTION: _extract_named_bullets
# SUMMARY: Return the bullet list under a plain `Title:` heading, or "" when the source carries none.
def _extract_named_bullets(shared_rules: str, title: str) -> str:
    match = re.search(rf"^{re.escape(title)}:\n((?:- .+\n?)+)", shared_rules, re.MULTILINE)
    return match.group(1).rstrip() if match else ""


# FUNCTION: malformed_section_headings
# SUMMARY: Present-but-unparseable hand-placed headings, so build_documents refuses a wrapper built on a guess.
def malformed_section_headings(shared_rules: str) -> list[str]:
    return [
        f"{title}:"
        for title in _HAND_PLACED_SECTION_TITLES
        if f"{title}:" in shared_rules and not _extract_named_bullets(shared_rules, title)
    ]


# CLASS: DroppedSectionError
# SUMMARY: Raised when a bullet section in the shared source reaches no generated wrapper.
class DroppedSectionError(RuntimeError):
    def __init__(self, headings: list[str]) -> None:
        self.headings = headings
        super().__init__(
            "Section(s) in docs/agent_rules.md reach no generated wrapper: "
            + "; ".join(headings)
            + ". Use a plain `Title:` line immediately followed by its bullets, no other punctuation."
        )


# FUNCTION: _render_wrapper
# SUMMARY: Render one agent's wrapper; identical body for every reader, name and reader read off target.
def _render_wrapper(shared_rules: str, target: Path) -> str:
    name = target.name
    reader = WRAPPER_READERS[target]
    quick_start = _extract_named_bullets(shared_rules, "Start here")
    task_process = _extract_named_bullets(shared_rules, "Task process")
    working_notes = _extract_named_bullets(shared_rules, "Working notes")
    task_process_section = f"## Task Process\n\n{task_process}\n\n" if task_process else ""
    additional = [
        f"## {title}\n\n{bullets.rstrip()}\n"
        for title, bullets in _NAMED_SECTION_PATTERN.findall(shared_rules)
        if title not in _SECTIONS_RENDERED_SEPARATELY
    ]
    additional_sections = "\n".join(additional) + "\n" if additional else ""
    python_minimum, python_toolchain = render_python_versions()
    return (
        f"# {name}\n\n"
        f"The shared Mayak agent rules, rendered for {reader}.\n\n"
        "Generated from `docs/agent_rules.md` via `scripts/sync_agent_docs.py`. Do not edit this file manually.\n\n"
        "## Quick Start\n\n"
        f"{quick_start}\n\n"
        "Running the service needs one more decision: the shipped `.env` points at PostgreSQL with\n"
        "placeholder credentials, so `make run-local` fails until either a database is up\n"
        "(`docker compose -f docker-compose.yml -f docker-compose.postgres.yml up -d db`) or the\n"
        "project declares it needs none (`POSTGRES_ENABLED=false` in `.env`).\n\n"
        # make help reads the Makefile live, so unlike a rendered copy it cannot fall out of step.
        "Run `make help` for the full grouped command list — it reads the Makefile directly.\n\n"
        f"{task_process_section}"
        "## Working Notes\n\n"
        f"{working_notes}\n"
        f"- `{name}` is a generated file and must not be edited directly. "
        "Edit `docs/agent_rules.md` instead, then run `make refresh-agent-docs`.\n\n"
        f"{additional_sections}"
        "## Tech Stack\n\n"
        f"- **Python**: {python_minimum}+ (runtime min), {python_toolchain} (dev toolchain)\n"
        "- **Package manager**: uv\n"
        "- **Framework**: FastAPI + Uvicorn\n"
        "- **Database**: PostgreSQL — psycopg at runtime; SQLAlchemy only as Alembic metadata\n"
        "- **Migrations**: Alembic\n"
        "- **LLM**: OpenAI-compatible API via langchain-openai (no graph library ships by default)\n"
        "- **Observability**: semantic NDJSON logging with trace trees\n"
        "- **Linting**: ruff (format + check)\n"
        f"- **Type checking**: mypy (target Python {python_minimum})\n"
        "- **Testing**: pytest + pytest-asyncio + httpx\n"
    )


# FUNCTION: build_documents
# SUMMARY: Build wrapper contents for every agent-facing file, refusing an unparseable or dropped section.
def build_documents() -> dict[Path, str]:
    shared_rules = SHARED_RULES_PATH.read_text(encoding="utf-8")
    malformed = malformed_section_headings(shared_rules)
    if malformed:
        raise DroppedSectionError(malformed)
    documents = {target: _render_wrapper(shared_rules, target) for target in WRAPPER_READERS}
    dropped = dropped_section_headings(shared_rules, documents)
    if dropped:
        raise DroppedSectionError(dropped)
    return documents


# FUNCTION: dropped_section_headings
# SUMMARY: Bullet sections whose bullets reach no wrapper — a looser net than rendering, so a
#          heading the strict pattern misses (bold, a trailing period) is caught, not just silently dropped.
def dropped_section_headings(shared_rules: str, documents: dict[Path, str]) -> list[str]:
    rendered_text = "\n".join(documents.values())
    dropped: list[str] = []
    heading: str | None = None
    inside_block = False
    for line in shared_rules.splitlines():
        stripped = line.strip()
        if stripped.startswith("- "):
            if not inside_block and heading is not None and stripped not in rendered_text:
                if heading not in dropped:
                    dropped.append(heading)
            inside_block = True
            continue
        inside_block = False
        if not stripped or stripped.startswith("#"):
            continue
        if ":" in stripped:
            heading = stripped
    return dropped


# FUNCTION: _fail
# SUMMARY: Report one structured drift issue (JSON with --json, else a plain message) and return 1.
def _fail(
    rule_id: str, file: str, message: str, suggested_fix: str, read_first: list[str], as_json: bool
) -> int:
    issue = {
        "rule_id": rule_id,
        "category": "drift",
        "file": file,
        "line": 1,
        "message": message,
        "suggested_fix": suggested_fix,
        "read_first": read_first,
        "next_commands": _NEXT_COMMANDS,
    }
    if as_json:
        print(render_json({"status": "error", "issues": [issue]}), end="")
    else:
        print(message)
    return 1


_SHARED_DISPLAY = _display_path(SHARED_RULES_PATH)
_READ_FIRST = [_SHARED_DISPLAY, "CLAUDE.md"]
_FIX = "Regenerate the agent wrappers from docs/agent_rules.md."


# FUNCTION: _check
# SUMMARY: Compare one rendered wrapper against disk; report and return 1 when it drifted, else 0.
def _check(path: Path, rendered: str, as_json: bool) -> int:
    if not path.exists():
        rule_id, verb = "drift.agent_docs.missing", "Missing"
    elif path.read_text(encoding="utf-8") != rendered:
        rule_id, verb = "drift.agent_docs.outdated", "Outdated"
    else:
        return 0
    display = _display_path(path)
    return _fail(rule_id, display, f"{verb} generated file: {display}", _FIX, _READ_FIRST, as_json)


# FUNCTION: main
# SUMMARY: Generate the agent wrappers or verify that the checked-in copies are current.
def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or verify the agent wrappers from docs/agent_rules.md."
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    try:
        rendered_documents = build_documents()
    except DroppedSectionError as error:
        fix = "Rewrite the heading as a plain `Title:` line, then regenerate."
        read_first = [_SHARED_DISPLAY, "scripts/sync_agent_docs.py"]
        return _fail(
            DROPPED_SECTION_RULE_ID, _SHARED_DISPLAY, str(error), fix, read_first, args.json
        )

    if not args.check:
        for path, rendered in rendered_documents.items():
            path.write_text(rendered, encoding="utf-8")
            print(f"Wrote {_display_path(path)}")
        return 0

    for path, rendered in rendered_documents.items():
        code = _check(path, rendered, args.json)
        if code:
            return code
    if args.json:
        print(render_json({"status": "ok", "issues": []}), end="")
    else:
        print(f"{len(rendered_documents)} agent wrappers are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
